---
title: "Curriculum Vitae"
---

Experience
Intramural Sports Official, Bates College, December 2022 - Present 
•	Worked within a team of officials responsible for all aspects of student intramural athletics experience
•	Responsibilities included set up/break down of activities, game officiation, conflict resolution 
•	Trained and mentored new officials to uphold the standards and rules of the games, 

Member Services, Beacon Hill Athletic Club, Brookline, MA December 2021- January 2023 
•	Provided excellent customer service, addressing member inquiries and resolving issues promptly
•	Maintained the cleanliness and organization of the facility, ensuring a welcoming environment

Ice Cream Scooper, Chill on Park, Dorchester, MA Summer 2022
•	Ensured accuracy and quality of orders, leading to increased customer satisfaction and repeat business
•	Collaborated with team members to maintain a clean and organized workspace

Sales Runner, Crimson Bikes, Cambridge, MA March-August 2021
•	Assisted customers with product inquiries, providing detailed and accurate product information
•	Maintained inventory and organized stock, supporting sales staff

Student Teacher, The Calculus Project, Brookline High School, Summer 2019-2020
•	Assisted in teaching math to students of color, promoting advancement in high school math courses
•	Developed lesson plans through collaboration with teachers 
•	Hosted tutoring sessions to meet individual student needs
